name = "bun-elysiajs-cfworkers-template"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"

[env.production]
name = "bun-elysiajs-cfworkers-template-production"